---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: layout
  label: layout
  default: project
  hidden: true
- type: text
  name: name
  label: name
- type: text
  name: status
  label: status
- type: number
  name: year
  label: year
- type: boolean
  name: featured
  label: featured
- type: textarea
  name: about
  label: about
pages:
- _projects/Hoot.md
